spring.application.name=Notiva

server.port=8080

spring.data.mongodb.uri=mongodb://localhost:27017/notiva_db

spring.security.user.name=aniket
spring.security.user.password=$2a$12$5PMeIJaP36z1adx8SE20CunmvJBKgO9SDgUXJXNOoUGXTsMFnuq.u
