spring.application.name=Notiva

server.port=8080

spring.data.mongodb.uri=mongodb+srv://aniketkelwa09:1234@cluster0.p2xjyzs.mongodb.net/notiva_db

#spring.security.user.name=aniket
#spring.security.user.password=$2a$12$5PMeIJaP36z1adx8SE20CunmvJBKgO9SDgUXJXNOoUGXTsMFnuq.u
